### ISSUE TITLE
After using, Recent list doesn't sync properly.

### ISSUE THREAD

**Issue by mnmkay** [8LWXpg/vscdb-workspace-storage-cleanup#3] opened 2024-03-18 12:54 UTC
### Description

I've just tried the extension and ran into problems. It seems my session went as follows:

1. Using vscdb: Cleanup: Recently Opened Files: I toggled and removed all missing files. The removed files seemed to successfully removed from VSCode "Open Recent" list.
2. Using vscdb: Cleanup: Recently Opened Folders: I toggled and removed all missing folders. The removed folders were NOT removed from VSCode "Open Recent" list.
3. Disappointed, to see if it would update the list, I manually removed a folder from VSCode "Open Recent" list (by clicking X next to it, in the Quick Open list for it.). No change.
4. I reloaded the window to see VSCode to see if that syncs the list. No. I restarted VSCode completely. No. I restarted a second time.
5. The folders seemed to be removed from the list this time. However, the files that I removed in Step 1 were back in the list, like I had never removed them. (I didn't check their presence in Step 4).
6. Retrying multiple times removing files and folders again, then restarting VSCode relatively quickly without changing anything else seems like the only thing that "reliably" will remove and keep them removed.

I am now realizing that Step 1 might not have functioned properly either because I was checking this extensions list when activating the "vscdb: *" commands. But that list that populates is not in sync with VSCode's Open Recent list after you use the extension to remove files and folders. The extensions thinks they're gone but VSCode does not. This is desync is possibly interfering with VSCode, so that the vscdb VSCode sees (in memory) can overwrite/conflict with your changes - possibly a recipe for vscdb issues. My recent lists are quite long by the way.

Either way, I've tested more now, and from the experience it seems that using this extension for either files or folders does not update the Open Recent list. And it at a minimum it requires a VSCode restart to sync - and probably, "safest", an immediate restart, after making recent list changes to vscdb.

If the VSCode API can't allow the "Open Recent" list can't be made to sync changes and/or without a VSCode feature request, then perhaps for now a warning before and after using this extensions should be issued about it requiring immediate restart to be safe.

Well..Unless the Open Recent lists *should* be updating after making changes.. so in that case this bug report should simply reflect that: for me, after using this extension, neither files/folders are actually removed from VSCode's Open Recent unless/until a full immediate application restart.

Am I the only one seeing this?

### Architecture

Windows x64

**Comment by 8LWXpg** [comment] 2024-03-18 13:25
The issue likely stems from Visual Studio Code not refreshing the list in real-time. To verify this, you can inspect the `state.vscdb` file located at `~\AppData\Roaming\Code\User\globalStorage` using an [SQLite browser](https://github.com/sqlitebrowser/sqlitebrowser). Check if the `history.recentlyOpenedPathsList` value updates after the deletion.

**Comment by 8LWXpg** [comment] 2024-07-31 13:57
Close this issue as it is not a bug related to the extension, nor is it resolvable through the extension.

**Closed as completed by 8LWXpg** 2024-07-31 13:57 UTC
Labels: bug
